# Generated by Django 4.0 on 2021-12-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0004_pontoturistico_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='comentario',
            new_name='comentarios',
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='avaliacoes',
            field=models.ManyToManyField(to='avaliacoes.Avaliacao'),
        ),
    ]
